# Generated by Django 5.1.5 on 2025-02-03 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_status'),
        ('status', '0002_seed_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='status.status'),
        ),
    ]
